### ISSUE TITLE
에러 핸들링 미들웨어 작성

### ISSUE THREAD

**Issue by m-dzn** [m-dzn/TinCase#2]
## 개선점

에러 처리 로직은 **가독성**과 **재사용성**, **유지보수성**을 높일 수 있는
**횡단 관심사**(ex: Spring AOP)에 해당됩니다.

처음 구현할 땐 모든 controller 모듈에
**비즈니스 로직과 try/catch문을 함께 넣었지만**

프로젝트가 점점 커지면서 에러 처리 코드 관리가 어려워지고 있습니다.

이에 **에러 핸들링용 미들웨어**를 작성해 코드 관리 효율을 높이는 쪽으로 코드를 개선하고자 합니다.

## Task 목록
- [x] async/await 방식으로 구현하기
- [x] 컨트롤러에서 에러 정보 받아오기
- HTTP 상태 코드
- 에러 메세지 등
- [x] HTTP Response에 JSON 형식으로 에러 정보를 담아서 반환
